spring:
  port: 8080
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
  h2:
    console:
      enabled: true
app:
  creditoApi:
    url: http://imersao-credito-api.herokuapp.com/credito/